### ISSUE TITLE
tic tac toe

### ISSUE THREAD

**Issue by earney** [pcarbonn/pyDatalog#11]
Enclosed is my attempt of translating the tic tac toe from https://courses.cs.washington.edu/courses/cse341/03sp/slides/PrologEx/tictactoe.pl.txt  to pyDatalog:
  
[tictactoe.txt](https://github.com/pcarbonn/pyDatalog/files/36814/tictactoe.txt)

It seems to hang up with an equals_primitive error at line 28:

```
Traceback (most recent call last):
  File "./tictactoe.py", line 57, in <module>
    game(Board, Player) <= win(Board, Player) & display(Board)
  File "./tictactoe.py", line 28, in win
    if Board[_x] == Board[_x+3] == Board[_x+6] == Player:
  File "/usr/local/lib/python3.4/dist-packages/pyDatalog/UserList.py", line 31, in __len__
    def __len__(self): return len(self.data)
  File "/usr/local/lib/python3.4/dist-packages/pyDatalog/pyParser.py", line 93, in data
    self.todo.ask()
  File "/usr/local/lib/python3.4/dist-packages/pyDatalog/pyParser.py", line 577, in ask
    self._data = Body(self.pre_calculations, self).ask()
  File "/usr/local/lib/python3.4/dist-packages/pyDatalog/pyParser.py", line 693, in ask
    self._data = literal.lua.ask()
  File "pyDatalog\pyEngine.py", line 511, in pyDatalog.pyEngine.Literal.ask (pyDatalog/pyEngine.c:18496)
  File "pyDatalog\pyEngine.py", line 734, in pyDatalog.pyEngine.Subgoal.search (pyDatalog/pyEngine.c:25415)
  File "pyDatalog\pyEngine.py", line 1110, in pyDatalog.pyEngine.equals_primitive (pyDatalog/pyEngine.c:35341)
AttributeError: 'pyDatalog.pyEngine.Operation' object has no attribute 'equals_primitive'
```

Any idea of how to overcome this?

**Comment by pcarbonn** [comment]
`win` and `display` in tictatoe.txt are python functions, not logic predicates.  You must use logic predicates in clauses, e.g. for `game(Board, Player)`.

Now, it is possible to define logic predicates using python functions, but you need to follow some rules, set out in

**Comment by pcarbonn** [comment]
It is also possible to use `win` and `display` as functions within logic expressions, as illustrated by the twice() function in the [tutorial](https://sites.google.com/site/pydatalog/Online-datalog-tutorial).

In that case, the `win` and `display` functions must be defined before `pyDatatlog.create_terms`, and they must be compared to True in an expression, e.g. `game(Board, Player) <= (win(Board, Player)==True) & (display(Board)==True)`.
