### ISSUE TITLE
wikipedia datalog example fails in pydatalog

### ISSUE THREAD

**Issue by earney** [pcarbonn/pyDatalog#12]
This example on datalog's wikipedia page https://en.wikipedia.org/wiki/Datalog#Example fails in pyDatalog:

```
 parent(bill, mary).
 parent(mary, john).
ancestor(X,Y) :- parent(X,Y).
 ancestor(X,Y) :- parent(X,Z),ancestor(Z,Y).
?- ancestor(bill,X).
```
I translate this to:
```
from pyDatalog import pyDatalog

pyDatalog.create_terms('parent,bill,mary,john,ancestor,X,Y,Z')

parent(bill, mary)
parent(mary, john)

ancestor(X,Y) <= parent(X,Y)
ancestor(X,Y) <= parent(X,Z), ancestor(Z,Y)

print(ancestor(bill,X))
```
and I get the following error:

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    print(ancestor(bill,X))
  File "/usr/local/lib/python3.4/dist-packages/pyDatalog/pyParser.py", line 134, in __str__
    return util.cast_to_str(self.__unicode__())
  File "/usr/local/lib/python3.4/dist-packages/pyDatalog/pyParser.py", line 604, in __unicode__
    return LazyListOfList.__unicode__(self)
  File "/usr/local/lib/python3.4/dist-packages/pyDatalog/pyParser.py", line 118, in __unicode__
    if self.data in (True, [], [()]): return util.unicode_type(self._data)
  File "/usr/local/lib/python3.4/dist-packages/pyDatalog/pyParser.py", line 93, in data
    self.todo.ask()
  File "/usr/local/lib/python3.4/dist-packages/pyDatalog/pyParser.py", line 577, in ask
    self._data = Body(self.pre_calculations, self).ask()
  File "/usr/local/lib/python3.4/dist-packages/pyDatalog/pyParser.py", line 693, in ask
    self._data = literal.lua.ask()
  File "pyDatalog\pyEngine.py", line 511, in pyDatalog.pyEngine.Literal.ask (pyDatalog/pyEngine.c:18496)
  File "pyDatalog\pyEngine.py", line 801, in pyDatalog.pyEngine.Subgoal.search (pyDatalog/pyEngine.c:27510)
AttributeError: Predicate without definition (or error in resolver): parent/2
```
I guess I need to define parent?  If so, what is the best way?

Any help is greatly appreciated!
Billy

**Comment by pcarbonn** [comment]
To assert a fact in pyDatalog, you need to prefix it with `+` (use`-` to retract it).  See [reference page](https://sites.google.com/site/pydatalog/reference) for all the syntax rules.

**Comment by earney** [comment]
the plus sign in front of parent helped, and then I also needed to replace the comma with an ampersand like so:

```
ancestor(X,Y) <= parent(X,Z) & ancestor(Z,Y)
```

**Comment by gulap** [comment]
The Above Code returns (with the commented + and &) "True" :-/
